spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/travelplanner}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    spring:
  datasource:
    url:postgresql://travel_db_955n_user:ww1KOkg7AjgcfY3hi2aQ8L3iApQIpYtF@dpg-danv6eegekts73aa6g3g-a/travel_db_955n
    username: travel_db_955n_user
    password: ww1K0kg7AjgcfY3hi2aQ8L3iApQIpYtFss
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
