package com.travelplanner.config;

import com.travelplanner.entity.*;
import com.travelplanner.repository.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@Component
public class DataInitializer implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DataInitializer.class);

    private final UserRepository userRepository;
    private final DestinationRepository destinationRepository;
    private final ActivityRepository activityRepository;
    private final RestaurantRepository restaurantRepository;
    private final TripRepository tripRepository;
    private final TripCollaboratorRepository tripCollaboratorRepository;
    private final ItineraryDayRepository itineraryDayRepository;
    private final ItineraryItemRepository itineraryItemRepository;
    private final ExpenseRepository expenseRepository;
    private final ExpenseSplitRepository expenseSplitRepository;
    private final PasswordEncoder passwordEncoder;

    public DataInitializer(UserRepository userRepository, DestinationRepository destinationRepository, ActivityRepository activityRepository, RestaurantRepository restaurantRepository, TripRepository tripRepository, TripCollaboratorRepository tripCollaboratorRepository, ItineraryDayRepository itineraryDayRepository, ItineraryItemRepository itineraryItemRepository, ExpenseRepository expenseRepository, ExpenseSplitRepository expenseSplitRepository, PasswordEncoder passwordEncoder) {
        this.userRepository = userRepository;
        this.destinationRepository = destinationRepository;
        this.activityRepository = activityRepository;
        this.restaurantRepository = restaurantRepository;
        this.tripRepository = tripRepository;
        this.tripCollaboratorRepository = tripCollaboratorRepository;
        this.itineraryDayRepository = itineraryDayRepository;
        this.itineraryItemRepository = itineraryItemRepository;
        this.expenseRepository = expenseRepository;
        this.expenseSplitRepository = expenseSplitRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    @Transactional
    public void run(String... args) {
        if (userRepository.count() > 0) {
            log.info("Database already contains data, skipping seed initializer.");
            return;
        }

        log.info("Seeding initial travel platform data...");

        User alex = User.builder()
                .email("demo@wanderlust.com")
                .passwordHash(passwordEncoder.encode("password123"))
                .fullName("Alex Morgan")
                .avatarUrl("https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80")
                .bio("Passionate globetrotter, photographer, and coffee enthusiast.")
                .homeAirport("SFO")
                .preferredCurrency("USD")
                .travelStyle("BALANCED")
                .travelInterests("Culture,Food,Nature,Photography")
                .budgetTier("MID_RANGE")
                .role(Role.ROLE_USER)
                .build();
        alex = userRepository.save(alex);

        User sarah = User.builder()
                .email("sarah.travels@world.com")
                .passwordHash(passwordEncoder.encode("password123"))
                .fullName("Sarah Jenkins")
                .avatarUrl("https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80")
                .bio("Adventure seeker & hiker exploring mountain trails across Europe & Asia.")
                .homeAirport("LHR")
                .preferredCurrency("EUR")
                .travelStyle("ADVENTURE")
                .travelInterests("Hiking,Architecture,Local Food,Diving")
                .budgetTier("LUXURY")
                .role(Role.ROLE_USER)
                .build();
        sarah = userRepository.save(sarah);

        User marcus = User.builder()
                .email("marcus.chen@explorer.io")
                .passwordHash(passwordEncoder.encode("password123"))
                .fullName("Marcus Chen")
                .avatarUrl("https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80")
                .bio("Architectural historian and street food connoisseur.")
                .homeAirport("SIN")
                .preferredCurrency("SGD")
                .travelStyle("CULTURE")
                .travelInterests("Museums,History,Nightlife,Art")
                .budgetTier("BALANCED")
                .role(Role.ROLE_USER)
                .build();
        marcus = userRepository.save(marcus);

        Destination tokyo = destinationRepository.save(Destination.builder()
                .name("Tokyo Metropolis")
                .city("Tokyo")
                .country("Japan")
                .continent("Asia")
                .heroImageUrl("https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=800&q=80,https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80,https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?auto=format&fit=crop&w=800&q=80")
                .description("A dazzling fusion of ultra-modern skyscrapers, neon-lit nightlife, historic temples, and world-class culinary innovation.")
                .vibeTags("Modern,Foodie,Culture,Shopping,Nightlife")
                .averageDailyCost(BigDecimal.valueOf(180.00))
                .currency("JPY")
                .latitude(35.6762)
                .longitude(139.6503)
                .rating(BigDecimal.valueOf(4.95))
                .reviewCount(1280)
                .popularSights("Shibuya Crossing, Senso-ji Temple, Shinjuku Gyoen, TeamLab Planets, Akihabara Electric Town")
                .bestTimeToVisit("March - May & September - November")
                .isFeatured(true)
                .build());

        Destination paris = destinationRepository.save(Destination.builder()
                .name("Paris Romance & Heritage")
                .city("Paris")
                .country("France")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=800&q=80,https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80")
                .description("The iconic City of Light, renowned for legendary haute cuisine, high fashion, world-class art museums, and charming café-lined boulevards.")
                .vibeTags("Romantic,Art,History,Foodie,Architecture")
                .averageDailyCost(BigDecimal.valueOf(210.00))
                .currency("EUR")
                .latitude(48.8566)
                .longitude(2.3522)
                .rating(BigDecimal.valueOf(4.88))
                .reviewCount(2450)
                .popularSights("Eiffel Tower, Louvre Museum, Notre-Dame, Montmartre & Sacré-Cœur, Seine River Cruise")
                .bestTimeToVisit("April - June & September - October")
                .isFeatured(true)
                .build());

        Destination bali = destinationRepository.save(Destination.builder()
                .name("Bali Tropical Sanctuary")
                .city("Ubud & Seminyak")
                .country("Indonesia")
                .continent("Asia")
                .heroImageUrl("https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80,https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=800&q=80")
                .description("An enchanting Indonesian paradise with emerald rice terraces, sacred sea temples, surf beaches, lush wellness resorts, and vibrant arts.")
                .vibeTags("Relaxed,Nature,Beach,Wellness,Adventure")
                .averageDailyCost(BigDecimal.valueOf(85.00))
                .currency("IDR")
                .latitude(-8.4095)
                .longitude(115.1889)
                .rating(BigDecimal.valueOf(4.82))
                .reviewCount(1980)
                .popularSights("Tegallalang Rice Terraces, Uluwatu Temple, Sacred Monkey Forest, Mount Batur Sunrise Hike")
                .bestTimeToVisit("April - October")
                .isFeatured(true)
                .build());

        Destination amalfi = destinationRepository.save(Destination.builder()
                .name("Amalfi Coast & Positano")
                .city("Amalfi")
                .country("Italy")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80")
                .description("Dramatic Mediterranean cliffs, pastel fishing villages clinging to cliffsides, azure waters, lemon groves, and authentic Southern Italian dining.")
                .vibeTags("Romantic,Scenic,Luxury,Foodie,Beach")
                .averageDailyCost(BigDecimal.valueOf(260.00))
                .currency("EUR")
                .latitude(40.6340)
                .longitude(14.6027)
                .rating(BigDecimal.valueOf(4.91))
                .reviewCount(890)
                .popularSights("Positano Cliffside Walk, Path of the Gods, Villa Rufolo Ravello, Capri Island Boat Tour")
                .bestTimeToVisit("May - September")
                .isFeatured(true)
                .build());

        Destination iceland = destinationRepository.save(Destination.builder()
                .name("Reykjavik & Wild Iceland")
                .city("Reykjavik")
                .country("Iceland")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1529963183134-61a90db47eaf?auto=format&fit=crop&w=800&q=80")
                .description("The land of fire and ice, boasting mystical Northern Lights, geothermal lagoons, roaring waterfalls, black sand beaches, and glaciers.")
                .vibeTags("Adventure,Nature,Scenic,Photography,Wellness")
                .averageDailyCost(BigDecimal.valueOf(240.00))
                .currency("ISK")
                .latitude(64.1466)
                .longitude(-21.9426)
                .rating(BigDecimal.valueOf(4.89))
                .reviewCount(1120)
                .popularSights("Blue Lagoon, Golden Circle, Gullfoss Waterfall, Reynisfjara Black Sand Beach")
                .bestTimeToVisit("September - March (Aurora) & June - August (Midnight Sun)")
                .isFeatured(true)
                .build());

        Destination rome = destinationRepository.save(Destination.builder()
                .name("Rome & Ancient Wonders")
                .city("Rome")
                .country("Italy")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&w=800&q=80")
                .description("The Eternal City showcasing ancient gladiatorial arenas, Vatican treasures, Renaissance fountains, and timeless pasta trattorias.")
                .vibeTags("Historical,Culture,Art,Foodie,Romantic")
                .averageDailyCost(BigDecimal.valueOf(190.00))
                .currency("EUR")
                .latitude(41.9028)
                .longitude(12.4964)
                .rating(BigDecimal.valueOf(4.93))
                .reviewCount(3100)
                .popularSights("Colosseum, Vatican Museums & St. Peter's, Trevi Fountain, Pantheon, Roman Forum")
                .bestTimeToVisit("April - June & September - October")
                .isFeatured(true)
                .build());

        Destination nyc = destinationRepository.save(Destination.builder()
                .name("New York City Skyline")
                .city("New York")
                .country("United States")
                .continent("North America")
                .heroImageUrl("https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=800&q=80")
                .description("The vibrant capital of culture, Broadway theater, world-class museums, Central Park serenity, and iconic skyscraper vistas.")
                .vibeTags("Urban,Modern,Culture,Shopping,Nightlife")
                .averageDailyCost(BigDecimal.valueOf(280.00))
                .currency("USD")
                .latitude(40.7128)
                .longitude(-74.0060)
                .rating(BigDecimal.valueOf(4.90))
                .reviewCount(4200)
                .popularSights("Central Park, Empire State Building, Times Square, Statue of Liberty, High Line & Summit One Vanderbilt")
                .bestTimeToVisit("April - June & September - December")
                .isFeatured(true)
                .build());

        Destination london = destinationRepository.save(Destination.builder()
                .name("London Royal Heritage")
                .city("London")
                .country("United Kingdom")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1520986606214-8b456906c813?auto=format&fit=crop&w=800&q=80")
                .description("Rich British royalty, historic Thames riverbanks, world-renowned free museums, West End musicals, and royal parks.")
                .vibeTags("Historical,Culture,Modern,Foodie,Shopping")
                .averageDailyCost(BigDecimal.valueOf(230.00))
                .currency("GBP")
                .latitude(51.5074)
                .longitude(-0.1278)
                .rating(BigDecimal.valueOf(4.87))
                .reviewCount(3500)
                .popularSights("Big Ben & Westminster, British Museum, Tower Bridge, Buckingham Palace, London Eye")
                .bestTimeToVisit("May - September")
                .isFeatured(true)
                .build());

        Destination kyoto = destinationRepository.save(Destination.builder()
                .name("Kyoto Imperial Temples")
                .city("Kyoto")
                .country("Japan")
                .continent("Asia")
                .heroImageUrl("https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80")
                .description("Ancient Japanese capital of thousands of vermilion torii gates, Zen stone gardens, bamboo groves, and traditional geisha districts.")
                .vibeTags("Cultural,Historical,Nature,Romantic,Foodie")
                .averageDailyCost(BigDecimal.valueOf(160.00))
                .currency("JPY")
                .latitude(35.0116)
                .longitude(135.7681)
                .rating(BigDecimal.valueOf(4.96))
                .reviewCount(1890)
                .popularSights("Fushimi Inari Shrine, Arashiyama Bamboo Grove, Kinkaku-ji Golden Pavilion, Gion District, Kiyomizu-dera")
                .bestTimeToVisit("March - May & October - November")
                .isFeatured(true)
                .build());

        Destination dubai = destinationRepository.save(Destination.builder()
                .name("Dubai Desert & Luxury Oasis")
                .city("Dubai")
                .country("United Arab Emirates")
                .continent("Asia")
                .heroImageUrl("https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80")
                .description("Futuristic skyline towering above Arabian golden dunes with luxury resorts, mega malls, and world-record marvels.")
                .vibeTags("Luxury,Modern,Urban,Adventure,Shopping")
                .averageDailyCost(BigDecimal.valueOf(270.00))
                .currency("AED")
                .latitude(25.2048)
                .longitude(55.2708)
                .rating(BigDecimal.valueOf(4.92))
                .reviewCount(2100)
                .popularSights("Burj Khalifa, Dubai Mall & Fountain, Palm Jumeirah, Desert Dune Safari, Museum of the Future")
                .bestTimeToVisit("November - March")
                .isFeatured(true)
                .build());

        Destination santorini = destinationRepository.save(Destination.builder()
                .name("Santorini Aegean Sunsets")
                .city("Santorini")
                .country("Greece")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80")
                .description("Whitewashed cliffside villas, cobalt-blue domes, volcanic vineyards, and world-famous golden sunsets over the Aegean caldera.")
                .vibeTags("Romantic,Scenic,Luxury,Beach,Relaxed")
                .averageDailyCost(BigDecimal.valueOf(250.00))
                .currency("EUR")
                .latitude(36.3932)
                .longitude(25.4615)
                .rating(BigDecimal.valueOf(4.94))
                .reviewCount(1750)
                .popularSights("Oia Sunset Viewpoint, Fira to Oia Caldera Hike, Red Beach, Akrotiri Ruins, Ammoudi Bay")
                .bestTimeToVisit("May - October")
                .isFeatured(true)
                .build());

        Destination barcelona = destinationRepository.save(Destination.builder()
                .name("Barcelona & Catalan Art")
                .city("Barcelona")
                .country("Spain")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=800&q=80")
                .description("Gaudí architectural wonderland, Mediterranean beach promenades, tapas bars, and lively Gothic Quarter alleyways.")
                .vibeTags("Cultural,Art,Foodie,Beach,Architecture")
                .averageDailyCost(BigDecimal.valueOf(175.00))
                .currency("EUR")
                .latitude(41.3879)
                .longitude(2.1699)
                .rating(BigDecimal.valueOf(4.88))
                .reviewCount(2800)
                .popularSights("Sagrada Família, Park Güell, Casa Batlló, Gothic Quarter, Barceloneta Beach")
                .bestTimeToVisit("May - June & September - October")
                .isFeatured(true)
                .build());

        Destination swissAlps = destinationRepository.save(Destination.builder()
                .name("Swiss Alps & Interlaken")
                .city("Interlaken & Zermatt")
                .country("Switzerland")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80")
                .description("Snowcapped Alpine peaks, turquoise glacial lakes, scenic cogwheel mountain trains, and picturesque chalet villages.")
                .vibeTags("Mountain,Scenic,Adventure,Nature,Luxury")
                .averageDailyCost(BigDecimal.valueOf(290.00))
                .currency("CHF")
                .latitude(46.6863)
                .longitude(7.8632)
                .rating(BigDecimal.valueOf(4.97))
                .reviewCount(1420)
                .popularSights("Jungfraujoch Top of Europe, Matterhorn Glacier Paradise, Lake Brienz, Lauterbrunnen Valley, Grindelwald First")
                .bestTimeToVisit("December - March (Ski) & June - September (Hiking)")
                .isFeatured(true)
                .build());

        Destination sydney = destinationRepository.save(Destination.builder()
                .name("Sydney Harbour & Beaches")
                .city("Sydney")
                .country("Australia")
                .continent("Oceania")
                .heroImageUrl("https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=800&q=80")
                .description("Iconic Opera House sails, sun-kissed Bondi surf, glittering harbor cruises, and coastal cliffside walks.")
                .vibeTags("Beach,Urban,Scenic,Modern,Adventure")
                .averageDailyCost(BigDecimal.valueOf(220.00))
                .currency("AUD")
                .latitude(-33.8688)
                .longitude(151.2093)
                .rating(BigDecimal.valueOf(4.89))
                .reviewCount(1650)
                .popularSights("Sydney Opera House, Sydney Harbour Bridge Climb, Bondi to Coogee Coastal Walk, Manly Ferry, Taronga Zoo")
                .bestTimeToVisit("September - November & March - May")
                .isFeatured(true)
                .build());

        Destination cairo = destinationRepository.save(Destination.builder()
                .name("Cairo & Giza Pyramids")
                .city("Cairo")
                .country("Egypt")
                .continent("Africa")
                .heroImageUrl("https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1539650116574-8efeb43e2750?auto=format&fit=crop&w=800&q=80")
                .description("5,000 years of civilization, the Great Pyramids of Giza, the mysterious Sphinx, bustling Khan el-Khalili souks, and Nile cruises.")
                .vibeTags("Historical,Cultural,Adventure,Photography")
                .averageDailyCost(BigDecimal.valueOf(95.00))
                .currency("EGP")
                .latitude(30.0444)
                .longitude(31.2357)
                .rating(BigDecimal.valueOf(4.85))
                .reviewCount(2300)
                .popularSights("Great Pyramid of Giza & Sphinx, Grand Egyptian Museum, Khan el-Khalili Bazaar, Nile River Felucca Ride")
                .bestTimeToVisit("October - April")
                .isFeatured(true)
                .build());

        Destination capeTown = destinationRepository.save(Destination.builder()
                .name("Cape Town Coastal Majesty")
                .city("Cape Town")
                .country("South Africa")
                .continent("Africa")
                .heroImageUrl("https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?auto=format&fit=crop&w=800&q=80")
                .description("A spectacular melting pot of rugged ocean cliffs, iconic Table Mountain peaks, wine valleys, penguin colonies, and vibrant culture.")
                .vibeTags("Adventure,Scenic,Foodie,Wildlife,Nature")
                .averageDailyCost(BigDecimal.valueOf(110.00))
                .currency("ZAR")
                .latitude(-33.9249)
                .longitude(18.4241)
                .rating(BigDecimal.valueOf(4.86))
                .reviewCount(740)
                .popularSights("Table Mountain Cable Car, Cape Point & Cape of Good Hope, Boulders Penguin Beach, Stellenbosch Wine Route, Camps Bay")
                .bestTimeToVisit("November - March")
                .isFeatured(true)
                .build());

        Destination rio = destinationRepository.save(Destination.builder()
                .name("Rio de Janeiro & Copacabana")
                .city("Rio de Janeiro")
                .country("Brazil")
                .continent("South America")
                .heroImageUrl("https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?auto=format&fit=crop&w=800&q=80")
                .description("Breathtaking seaside metropolis with Christ the Redeemer atop Corcovado, Sugarloaf Mountain cable cars, and samba beats.")
                .vibeTags("Beach,Cultural,Scenic,Adventure,Nightlife")
                .averageDailyCost(BigDecimal.valueOf(120.00))
                .currency("BRL")
                .latitude(-22.9068)
                .longitude(-43.1729)
                .rating(BigDecimal.valueOf(4.84))
                .reviewCount(1490)
                .popularSights("Christ the Redeemer, Sugarloaf Mountain, Copacabana Beach, Ipanema Beach, Selarón Steps")
                .bestTimeToVisit("December - March")
                .isFeatured(true)
                .build());

        Destination machuPicchu = destinationRepository.save(Destination.builder()
                .name("Machu Picchu & Sacred Valley")
                .city("Cusco & Machu Picchu")
                .country("Peru")
                .continent("South America")
                .heroImageUrl("https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1589802829985-817e51171b92?auto=format&fit=crop&w=800&q=80")
                .description("The legendary 15th-century Inca citadel nestled high in the Andean cloud forest, surrounded by mystical mountain peaks.")
                .vibeTags("Historical,Adventure,Mountain,Nature,Cultural")
                .averageDailyCost(BigDecimal.valueOf(135.00))
                .currency("PEN")
                .latitude(-13.1631)
                .longitude(-72.5450)
                .rating(BigDecimal.valueOf(4.98))
                .reviewCount(2600)
                .popularSights("Machu Picchu Citadel, Huayna Picchu Climb, Sacred Valley of the Incas, Cusco Historic Plaza, Rainbow Mountain")
                .bestTimeToVisit("May - September")
                .isFeatured(true)
                .build());

        Destination bangkok = destinationRepository.save(Destination.builder()
                .name("Bangkok Temples & Street Food")
                .city("Bangkok")
                .country("Thailand")
                .continent("Asia")
                .heroImageUrl("https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1563492065599-3520f775eeed?auto=format&fit=crop&w=800&q=80")
                .description("Vibrant Thai capital of shimmering golden palaces, buzzing night markets, Michelin-starred street stalls, and Chao Phraya river life.")
                .vibeTags("Foodie,Culture,Historical,Urban,Nightlife")
                .averageDailyCost(BigDecimal.valueOf(75.00))
                .currency("THB")
                .latitude(13.7563)
                .longitude(100.5018)
                .rating(BigDecimal.valueOf(4.86))
                .reviewCount(3100)
                .popularSights("Grand Palace & Emerald Buddha, Wat Arun (Temple of Dawn), Chatuchak Weekend Market, Chinatown Food Street, Floating Markets")
                .bestTimeToVisit("November - February")
                .isFeatured(true)
                .build());

        Destination singapore = destinationRepository.save(Destination.builder()
                .name("Singapore Futuristic Garden City")
                .city("Singapore")
                .country("Singapore")
                .continent("Asia")
                .heroImageUrl("https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1506351421178-63b52a2d2562?auto=format&fit=crop&w=800&q=80")
                .description("Ultra-modern metropolis blending futuristic Supertrees, Marina Bay infinity views, lush botanic gardens, and multicultural hawker centers.")
                .vibeTags("Modern,Foodie,Urban,Nature,Luxury")
                .averageDailyCost(BigDecimal.valueOf(210.00))
                .currency("SGD")
                .latitude(1.3521)
                .longitude(103.8198)
                .rating(BigDecimal.valueOf(4.91))
                .reviewCount(2400)
                .popularSights("Gardens by the Bay, Marina Bay Sands SkyPark, Jewel Changi Rain Vortex, Sentosa Island, Lau Pa Sat Hawker Market")
                .bestTimeToVisit("Year-round (Best: November - January)")
                .isFeatured(true)
                .build());

        Destination hawaii = destinationRepository.save(Destination.builder()
                .name("Maui & Hawaiian Tropical Islands")
                .city("Maui & Honolulu")
                .country("United States")
                .continent("North America")
                .heroImageUrl("https://images.unsplash.com/photo-1542259009477-d625272157b7?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80")
                .description("Polynesian paradise of golden sand beaches, Road to Hana waterfalls, Haleakala volcano sunrises, and sea turtle snorkeling.")
                .vibeTags("Beach,Nature,Adventure,Relaxed,Romantic")
                .averageDailyCost(BigDecimal.valueOf(265.00))
                .currency("USD")
                .latitude(20.7984)
                .longitude(-156.3319)
                .rating(BigDecimal.valueOf(4.94))
                .reviewCount(1800)
                .popularSights("Haleakala Crater Sunrise, Road to Hana, Kaanapali Beach, Molokini Crater Snorkel, Wailea Sunset")
                .bestTimeToVisit("April - May & September - November")
                .isFeatured(true)
                .build());

        Destination amsterdam = destinationRepository.save(Destination.builder()
                .name("Amsterdam Canals & Art")
                .city("Amsterdam")
                .country("Netherlands")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=800&q=80")
                .description("Charming 17th-century canal rings, Van Gogh and Rembrandt masterpieces, bicycle-lined bridges, and historic townhouse architecture.")
                .vibeTags("Cultural,Art,Historical,Urban,Romantic")
                .averageDailyCost(BigDecimal.valueOf(195.00))
                .currency("EUR")
                .latitude(52.3676)
                .longitude(4.9041)
                .rating(BigDecimal.valueOf(4.87))
                .reviewCount(2150)
                .popularSights("Rijksmuseum, Van Gogh Museum, Anne Frank House, Jordaan Canal District, Keukenhof Tulip Gardens")
                .bestTimeToVisit("April - May & September - November")
                .isFeatured(true)
                .build());

        Destination venice = destinationRepository.save(Destination.builder()
                .name("Venice Floating Romance")
                .city("Venice")
                .country("Italy")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=800&q=80")
                .description("Timeless floating sanctuary built upon 118 islands, connected by stone bridges, gondola-gliding canals, and Venetian Gothic palaces.")
                .vibeTags("Romantic,Historical,Art,Scenic,Cultural")
                .averageDailyCost(BigDecimal.valueOf(235.00))
                .currency("EUR")
                .latitude(45.4408)
                .longitude(12.3155)
                .rating(BigDecimal.valueOf(4.89))
                .reviewCount(1920)
                .popularSights("Piazza San Marco & Basilica, Doge's Palace, Grand Canal Gondola Ride, Rialto Bridge, Burano Colorful Island")
                .bestTimeToVisit("April - June & September - October")
                .isFeatured(true)
                .build());

        Destination prague = destinationRepository.save(Destination.builder()
                .name("Prague Bohemian Splendor")
                .city("Prague")
                .country("Czech Republic")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=800&q=80")
                .description("The City of a Hundred Spires featuring fairy-tale gothic castles, the medieval Astronomical Clock, and cobblestone charm.")
                .vibeTags("Historical,Romantic,Culture,Architecture")
                .averageDailyCost(BigDecimal.valueOf(115.00))
                .currency("CZK")
                .latitude(50.0755)
                .longitude(14.4378)
                .rating(BigDecimal.valueOf(4.88))
                .reviewCount(1780)
                .popularSights("Charles Bridge at Dawn, Prague Castle & St. Vitus, Old Town Square & Astronomical Clock, Petrin Hill")
                .bestTimeToVisit("May - September")
                .isFeatured(true)
                .build());

        Destination marrakech = destinationRepository.save(Destination.builder()
                .name("Marrakech & Sahara Wonders")
                .city("Marrakech")
                .country("Morocco")
                .continent("Africa")
                .heroImageUrl("https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80")
                .description("Vibrant North African jewel of labyrinthine spice medinas, cobalt Majorelle gardens, luxury riads, and golden desert stargazing.")
                .vibeTags("Cultural,Adventure,Historical,Foodie,Romantic")
                .averageDailyCost(BigDecimal.valueOf(90.00))
                .currency("MAD")
                .latitude(31.6295)
                .longitude(-7.9811)
                .rating(BigDecimal.valueOf(4.83))
                .reviewCount(1430)
                .popularSights("Jemaa el-Fnaa Square, Jardin Majorelle, Bahia Palace, Koutoubia Mosque, Sahara Desert Glamping Tour")
                .bestTimeToVisit("March - May & September - November")
                .isFeatured(true)
                .build());

        Destination banff = destinationRepository.save(Destination.builder()
                .name("Banff & Canadian Rockies")
                .city("Banff & Lake Louise")
                .country("Canada")
                .continent("North America")
                .heroImageUrl("https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=800&q=80")
                .description("Emerald glacial lakes, towering limestone Rockies peaks, wild grizzly habitats, and pristine wilderness hiking trails.")
                .vibeTags("Nature,Mountain,Scenic,Adventure,Photography")
                .averageDailyCost(BigDecimal.valueOf(210.00))
                .currency("CAD")
                .latitude(51.1784)
                .longitude(-115.5708)
                .rating(BigDecimal.valueOf(4.96))
                .reviewCount(1560)
                .popularSights("Lake Louise, Moraine Lake & Valley of Ten Peaks, Icefields Parkway, Banff Gondola, Johnston Canyon")
                .bestTimeToVisit("June - September (Hiking) & December - April (Ski)")
                .isFeatured(true)
                .build());

        Destination queenstown = destinationRepository.save(Destination.builder()
                .name("Queenstown & Southern Alps")
                .city("Queenstown")
                .country("New Zealand")
                .continent("Oceania")
                .heroImageUrl("https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1589871134015-38102a0a2dfa?auto=format&fit=crop&w=800&q=80")
                .description("The Adventure Capital of the World, framed by dramatic Lake Wakatipu, The Remarkables mountain range, and fjord cruises.")
                .vibeTags("Adventure,Mountain,Scenic,Nature,Wine")
                .averageDailyCost(BigDecimal.valueOf(195.00))
                .currency("NZD")
                .latitude(-45.0312)
                .longitude(168.6626)
                .rating(BigDecimal.valueOf(4.95))
                .reviewCount(1290)
                .popularSights("Milford Sound Cruise, Skyline Gondola & Luge, Lake Wakatipu Cruise, Shotover River Jet, Cardrona Alpine Resort")
                .bestTimeToVisit("December - February (Summer) & June - August (Ski)")
                .isFeatured(true)
                .build());

        Destination maldives = destinationRepository.save(Destination.builder()
                .name("Maldives Overwater Sanctuary")
                .city("Male & North Ari Atoll")
                .country("Maldives")
                .continent("Asia")
                .heroImageUrl("https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80")
                .description("Pure turquoise lagoons, secluded private overwater bungalows, manta ray coral reefs, and world-class barefoot luxury.")
                .vibeTags("Beach,Luxury,Romantic,Relaxed,Wellness")
                .averageDailyCost(BigDecimal.valueOf(380.00))
                .currency("USD")
                .latitude(3.2028)
                .longitude(73.2207)
                .rating(BigDecimal.valueOf(4.97))
                .reviewCount(1180)
                .popularSights("Overwater Villa Villa Stays, Manta Ray & Whale Shark Snorkel, Sunset Dolphin Cruise, Sandbank Dining")
                .bestTimeToVisit("November - April")
                .isFeatured(true)
                .build());

        Destination agra = destinationRepository.save(Destination.builder()
                .name("Agra & Taj Mahal Heritage")
                .city("Agra")
                .country("India")
                .continent("Asia")
                .heroImageUrl("https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80")
                .description("Home of the Taj Mahal — the world's most breathtaking ivory-white marble monument to eternal love and Mughal architecture.")
                .vibeTags("Historical,Culture,Romantic,Architecture")
                .averageDailyCost(BigDecimal.valueOf(65.00))
                .currency("INR")
                .latitude(27.1767)
                .longitude(78.0081)
                .rating(BigDecimal.valueOf(4.93))
                .reviewCount(3800)
                .popularSights("Taj Mahal Sunrise View, Agra Fort, Mehtab Bagh Gardens, Fatehpur Sikri")
                .bestTimeToVisit("October - March")
                .isFeatured(true)
                .build());

        Destination petra = destinationRepository.save(Destination.builder()
                .name("Petra Ancient Rose City")
                .city("Wadi Musa & Petra")
                .country("Jordan")
                .continent("Asia")
                .heroImageUrl("https://images.unsplash.com/photo-1579606032834-d922576b97b0?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80")
                .description("One of the New 7 Wonders of the World — an ancient Nabataean metropolis hand-carved into pink sandstone canyon cliffs.")
                .vibeTags("Historical,Adventure,Cultural,Photography")
                .averageDailyCost(BigDecimal.valueOf(140.00))
                .currency("JOD")
                .latitude(30.3285)
                .longitude(35.4444)
                .rating(BigDecimal.valueOf(4.96))
                .reviewCount(1650)
                .popularSights("The Treasury (Al-Khazneh), The Siq Gorge, The Monastery (Ad Deir), Petra by Night, High Place of Sacrifice")
                .bestTimeToVisit("March - May & September - November")
                .isFeatured(true)
                .build());

        Destination seoul = destinationRepository.save(Destination.builder()
                .name("Seoul K-Culture & Palaces")
                .city("Seoul")
                .country("South Korea")
                .continent("Asia")
                .heroImageUrl("https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=800&q=80")
                .description("Dynamic epicenter of K-pop, cutting-edge technology, Hanok heritage villages, royal Joseon palaces, and Korean BBQ.")
                .vibeTags("Modern,Foodie,Culture,Shopping,Nightlife")
                .averageDailyCost(BigDecimal.valueOf(145.00))
                .currency("KRW")
                .latitude(37.5665)
                .longitude(126.9780)
                .rating(BigDecimal.valueOf(4.90))
                .reviewCount(2100)
                .popularSights("Gyeongbokgung Palace, Bukchon Hanok Village, Myeongdong Street Market, N Seoul Tower, Hongdae Youth District")
                .bestTimeToVisit("March - May & September - November")
                .isFeatured(true)
                .build());

        Destination istanbul = destinationRepository.save(Destination.builder()
                .name("Istanbul Crossroads of Continents")
                .city("Istanbul")
                .country("Turkey")
                .continent("Europe")
                .heroImageUrl("https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1600&q=80")
                .galleryImages("https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80")
                .description("Where East meets West across the Bosphorus Strait — glorious Byzantine basilicas, Ottoman minarets, and the Grand Bazaar.")
                .vibeTags("Historical,Cultural,Foodie,Architecture")
                .averageDailyCost(BigDecimal.valueOf(105.00))
                .currency("TRY")
                .latitude(41.0082)
                .longitude(28.9784)
                .rating(BigDecimal.valueOf(4.91))
                .reviewCount(2950)
                .popularSights("Hagia Sophia, Blue Mosque, Topkapi Palace, Bosphorus Sunset Cruise, Grand Bazaar & Spice Market")
                .bestTimeToVisit("April - May & September - November")
                .isFeatured(true)
                .build());

        // Activities across top destinations
        activityRepository.saveAll(List.of(
                Activity.builder()
                        .destination(tokyo)
                        .name("Shibuya Sky & Harajuku Culture Walk")
                        .category("CULTURE")
                        .description("Panoramic 360-degree observation deck followed by a guided immersion into Takeshita street fashion and Meiji Shrine.")
                        .durationHours(BigDecimal.valueOf(3.5))
                        .price(BigDecimal.valueOf(45.00))
                        .currency("USD")
                        .rating(BigDecimal.valueOf(4.9))
                        .reviewCount(320)
                        .imageUrl("https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=600&q=80")
                        .address("2 Chome-24-12 Shibuya, Tokyo")
                        .openingHours("10:00 - 22:30")
                        .bookingRequired(true)
                        .build(),
                Activity.builder()
                        .destination(tokyo)
                        .name("TeamLab Planets Immersive Digital Art")
                        .category("MUSEUM")
                        .description("Walk through water and interactive crystal universes in this world-famous digital museum.")
                        .durationHours(BigDecimal.valueOf(2.0))
                        .price(BigDecimal.valueOf(38.00))
                        .currency("USD")
                        .rating(BigDecimal.valueOf(4.88))
                        .reviewCount(890)
                        .imageUrl("https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=600&q=80")
                        .address("6 Chome-1-16 Toyosu, Koto City, Tokyo")
                        .openingHours("09:00 - 22:00")
                        .bookingRequired(true)
                        .build(),
                Activity.builder()
                        .destination(paris)
                        .name("Louvre Masterpieces with Art Historian")
                        .category("MUSEUM")
                        .description("Skip-the-line VIP access to the Mona Lisa, Venus de Milo, and Winged Victory with in-depth stories.")
                        .durationHours(BigDecimal.valueOf(3.0))
                        .price(BigDecimal.valueOf(75.00))
                        .currency("USD")
                        .rating(BigDecimal.valueOf(4.92))
                        .reviewCount(620)
                        .imageUrl("https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=600&q=80")
                        .address("Rue de Rivoli, 75001 Paris")
                        .openingHours("09:00 - 18:00")
                        .bookingRequired(true)
                        .build(),
                Activity.builder()
                        .destination(paris)
                        .name("Sunset Champagne Seine River Cruise")
                        .category("SIGHTSEEING")
                        .description("Glaze through illuminated Parisian bridges and the sparkling Eiffel Tower with French champagne.")
                        .durationHours(BigDecimal.valueOf(1.5))
                        .price(BigDecimal.valueOf(35.00))
                        .currency("USD")
                        .rating(BigDecimal.valueOf(4.85))
                        .reviewCount(950)
                        .imageUrl("https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=600&q=80")
                        .address("Port de la Bourdonnais, 75007 Paris")
                        .openingHours("18:00 - 23:00")
                        .bookingRequired(true)
                        .build(),
                Activity.builder()
                        .destination(bali)
                        .name("Mount Batur Sunrise Trek & Hot Springs")
                        .category("ADVENTURE")
                        .description("Early morning volcanic hike with breathtaking caldera sunrise breakfast and thermal spring soak.")
                        .durationHours(BigDecimal.valueOf(6.0))
                        .price(BigDecimal.valueOf(55.00))
                        .currency("USD")
                        .rating(BigDecimal.valueOf(4.91))
                        .reviewCount(540)
                        .imageUrl("https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=600&q=80")
                        .address("Kintamani, Bangli Regency, Bali")
                        .openingHours("03:00 - 12:00")
                        .bookingRequired(true)
                        .build(),
                Activity.builder()
                        .destination(rome)
                        .name("Colosseum Underground & Gladiators Arena")
                        .category("HISTORICAL")
                        .description("Exclusive VIP underground tunnel access and Roman Forum exploration with archaeologist guide.")
                        .durationHours(BigDecimal.valueOf(3.0))
                        .price(BigDecimal.valueOf(68.00))
                        .currency("USD")
                        .rating(BigDecimal.valueOf(4.94))
                        .reviewCount(1120)
                        .imageUrl("https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80")
                        .address("Piazza del Colosseo, 1, 00184 Roma RM")
                        .openingHours("08:30 - 19:00")
                        .bookingRequired(true)
                        .build(),
                Activity.builder()
                        .destination(nyc)
                        .name("Summit One Vanderbilt & High Line Sunset")
                        .category("SIGHTSEEING")
                        .description("Multisensory glass skydeck views overlooking Manhattan, followed by a scenic High Line park walk.")
                        .durationHours(BigDecimal.valueOf(2.5))
                        .price(BigDecimal.valueOf(48.00))
                        .currency("USD")
                        .rating(BigDecimal.valueOf(4.93))
                        .reviewCount(1430)
                        .imageUrl("https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=600&q=80")
                        .address("45 E 42nd St, New York, NY 10017")
                        .openingHours("09:00 - 00:00")
                        .bookingRequired(true)
                        .build(),
                Activity.builder()
                        .destination(machuPicchu)
                        .name("Machu Picchu Citadel Sunrise Guided Tour")
                        .category("HISTORICAL")
                        .description("Witness sunrise over the lost city of the Incas with expert Andean cultural interpretation.")
                        .durationHours(BigDecimal.valueOf(4.0))
                        .price(BigDecimal.valueOf(85.00))
                        .currency("USD")
                        .rating(BigDecimal.valueOf(4.99))
                        .reviewCount(2100)
                        .imageUrl("https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=600&q=80")
                        .address("Machu Picchu Sanctuary, Aguas Calientes, Cusco")
                        .openingHours("06:00 - 17:30")
                        .bookingRequired(true)
                        .build(),
                Activity.builder()
                        .destination(agra)
                        .name("Taj Mahal Sunrise & Mughal Heritage Walk")
                        .category("HISTORICAL")
                        .description("Golden hour sunrise photography tour of the Taj Mahal followed by Mughal craft demonstration.")
                        .durationHours(BigDecimal.valueOf(3.5))
                        .price(BigDecimal.valueOf(30.00))
                        .currency("USD")
                        .rating(BigDecimal.valueOf(4.96))
                        .reviewCount(1800)
                        .imageUrl("https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=600&q=80")
                        .address("Dharmapuri, Forest Colony, Tajganj, Agra, Uttar Pradesh")
                        .openingHours("06:00 - 18:30")
                        .bookingRequired(true)
                        .build()
        ));

        // Restaurants across top destinations
        restaurantRepository.saveAll(List.of(
                Restaurant.builder()
                        .destination(tokyo)
                        .name("Afuri Ramen & Craft Brews")
                        .cuisineType("Japanese Ramen")
                        .priceRange("$$")
                        .rating(BigDecimal.valueOf(4.8))
                        .reviewCount(480)
                        .address("1 Chome-1-7 Ebisu, Shibuya City, Tokyo")
                        .openingHours("11:00 - 23:00")
                        .specialties("Yuzu Shio Ramen, Charcoal Grilled Pork, Vegan Ramen")
                        .imageUrl("https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80")
                        .reservationUrl("https://afuri.com")
                        .build(),
                Restaurant.builder()
                        .destination(paris)
                        .name("Le Coupe-Chou Latin Quarter")
                        .cuisineType("Traditional French")
                        .priceRange("$$$")
                        .rating(BigDecimal.valueOf(4.7))
                        .reviewCount(340)
                        .address("11 Rue de Laveau-le-Vicomte, 75005 Paris")
                        .openingHours("12:00 - 23:00")
                        .specialties("Boeuf Bourguignon, Duck Confit, Soufflé au Chocolat")
                        .imageUrl("https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=600&q=80")
                        .reservationUrl("https://lecoupechou.com")
                        .build(),
                Restaurant.builder()
                        .destination(bali)
                        .name("Locavore Herbivore Ubud")
                        .cuisineType("Modern Indonesian Farm-to-Table")
                        .priceRange("$$$")
                        .rating(BigDecimal.valueOf(4.9))
                        .reviewCount(290)
                        .address("Jl. Dewi Sita No.10, Ubud, Bali")
                        .openingHours("12:00 - 22:00")
                        .specialties("Smoked Heirloom Tomatoes, Bali Truffle Rice, Fermented Mango Glaze")
                        .imageUrl("https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80")
                        .reservationUrl("https://locavorenext.com")
                        .build(),
                Restaurant.builder()
                        .destination(rome)
                        .name("Trattoria Da Enzo al 29")
                        .cuisineType("Roman Classic")
                        .priceRange("$$")
                        .rating(BigDecimal.valueOf(4.88))
                        .reviewCount(520)
                        .address("Via dei Vascellari, 29, 00153 Roma RM")
                        .openingHours("12:30 - 23:00")
                        .specialties("Cacio e Pepe, Carbonara, Artichokes Alla Giudia, Tiramisu")
                        .imageUrl("https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80")
                        .reservationUrl("https://daenzoal29.com")
                        .build(),
                Restaurant.builder()
                        .destination(nyc)
                        .name("Gramercy Tavern Manhattan")
                        .cuisineType("Contemporary American")
                        .priceRange("$$$$")
                        .rating(BigDecimal.valueOf(4.91))
                        .reviewCount(680)
                        .address("42 E 20th St, New York, NY 10003")
                        .openingHours("11:30 - 23:00")
                        .specialties("Wood-Fired Duck Breast, Hand-rolled Pasta, Roasted Sea Bass")
                        .imageUrl("https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80")
                        .reservationUrl("https://gramercytavern.com")
                        .build()
        ));

        Trip sampleTrip = Trip.builder()
                .owner(alex)
                .destination(tokyo)
                .title("Tokyo Sakura Discovery 2026")
                .description("An unforgettable 5-day journey through Tokyo futuristic sights, cherry blossoms, historic shrines, and culinary legends.")
                .coverImageUrl("https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80")
                .startDate(LocalDate.of(2026, 10, 10))
                .endDate(LocalDate.of(2026, 10, 14))
                .totalDays(5)
                .travelerCount(2)
                .travelerType("COUPLE")
                .targetBudget(BigDecimal.valueOf(3500.00))
                .actualSpend(BigDecimal.valueOf(1420.00))
                .currency("USD")
                .status(Trip.TripStatus.PLANNING)
                .privacy(Trip.TripPrivacy.SHARED)
                .shareCode("tokyo-exp-2026-xyz")
                .build();
        sampleTrip = tripRepository.save(sampleTrip);

        TripCollaborator collabOwner = TripCollaborator.builder()
                .trip(sampleTrip)
                .user(alex)
                .role(TripCollaborator.CollaboratorRole.OWNER)
                .inviteStatus(TripCollaborator.InviteStatus.ACCEPTED)
                .build();
        tripCollaboratorRepository.save(collabOwner);

        TripCollaborator collabSarah = TripCollaborator.builder()
                .trip(sampleTrip)
                .user(sarah)
                .role(TripCollaborator.CollaboratorRole.EDITOR)
                .inviteStatus(TripCollaborator.InviteStatus.ACCEPTED)
                .build();
        tripCollaboratorRepository.save(collabSarah);

        for (int i = 1; i <= 5; i++) {
            ItineraryDay day = ItineraryDay.builder()
                    .trip(sampleTrip)
                    .dayNumber(i)
                    .date(LocalDate.of(2026, 10, 9 + i))
                    .title("Day " + i + " Adventure")
                    .notes("Explore Tokyo highlights and local cuisine")
                    .build();
            day = itineraryDayRepository.save(day);

            if (i == 1) {
                ItineraryItem flightItem = ItineraryItem.builder()
                        .day(day)
                        .itemType(ItineraryItem.ItemType.FLIGHT)
                        .title("Flight JL001: SFO to NRT")
                        .description("Direct flight arriving in Narita Tokyo at 14:30.")
                        .locationName("Narita International Airport")
                        .address("Narita, Chiba")
                        .startTime(LocalTime.of(14, 30))
                        .endTime(LocalTime.of(16, 0))
                        .estimatedCost(BigDecimal.valueOf(850.00))
                        .currency("USD")
                        .displayOrder(0)
                        .status(ItineraryItem.ItemStatus.BOOKED)
                        .build();
                itineraryItemRepository.save(flightItem);

                ItineraryItem hotelItem = ItineraryItem.builder()
                        .day(day)
                        .itemType(ItineraryItem.ItemType.ACCOMMODATION)
                        .title("Check-in: Park Hyatt Tokyo")
                        .description("Iconic Shinjuku high-rise hotel overlooking the city skyline.")
                        .locationName("Park Hyatt Tokyo")
                        .address("3-7-1-2 Nishi-Shinjuku, Tokyo")
                        .startTime(LocalTime.of(17, 0))
                        .endTime(LocalTime.of(18, 0))
                        .estimatedCost(BigDecimal.valueOf(320.00))
                        .currency("USD")
                        .displayOrder(1)
                        .status(ItineraryItem.ItemStatus.BOOKED)
                        .build();
                itineraryItemRepository.save(hotelItem);
            } else if (i == 2) {
                ItineraryItem sightItem = ItineraryItem.builder()
                        .day(day)
                        .itemType(ItineraryItem.ItemType.ACTIVITY)
                        .title("Senso-ji Temple & Nakamise Street")
                        .description("Tokyo oldest ancient Buddhist temple and traditional street crafts.")
                        .locationName("Senso-ji Temple")
                        .address("2 Chome-3-1 Asakusa, Taito City, Tokyo")
                        .startTime(LocalTime.of(9, 0))
                        .endTime(LocalTime.of(11, 30))
                        .estimatedCost(BigDecimal.ZERO)
                        .currency("USD")
                        .displayOrder(0)
                        .status(ItineraryItem.ItemStatus.PLANNED)
                        .build();
                itineraryItemRepository.save(sightItem);
            }
        }

        Expense exp1 = Expense.builder()
                .trip(sampleTrip)
                .title("Flight Tickets (x2 SFO-NRT)")
                .category(Expense.ExpenseCategory.FLIGHTS)
                .amount(BigDecimal.valueOf(1700.00))
                .currency("USD")
                .convertedAmount(BigDecimal.valueOf(1700.00))
                .paidByUser(alex)
                .splitType(Expense.SplitType.EQUAL)
                .date(LocalDate.of(2026, 10, 1))
                .notes("Direct booking on JAL")
                .build();
        exp1 = expenseRepository.save(exp1);

        ExpenseSplit split1A = ExpenseSplit.builder().expense(exp1).user(alex).amountOwed(BigDecimal.valueOf(850.00)).isPaid(true).build();
        ExpenseSplit split1B = ExpenseSplit.builder().expense(exp1).user(sarah).amountOwed(BigDecimal.valueOf(850.00)).isPaid(false).build();
        expenseSplitRepository.saveAll(List.of(split1A, split1B));

        log.info("Initial data seed completed successfully!");
    }
}
